### ISSUE TITLE
repository documentation, README, and name

### ISSUE THREAD

**Issue by holgerdell** [PACE-challenge/Minimum-Fill-In-PACE-2017-instances#2]
Thanks for publishing the instances here!

See this repository for a possible template: https://github.com/PACE-challenge/Treewidth-PACE-2017-instances

Could you please:
- (important) add a LICENSE file
- add a link to the report (and/or the website) to the README file, and briefly mention the name of the problem that was solved.
- briefly explain the file format (do vertex names start at 0 or 1? etc) or link to a page that does.
- rename the repository consistent with other repositories at https://github.com/PACE-challenge, so either "problemname" (if this is meant to be a central hub also for future updates) or something that follows the pattern [problemname]-PACE-2017-instances (if this is just an archive of past instances)

Possibly:
- add solutions or correct answers where known, in the file format that was requested by the PACE-2017 challenge.

**Comment by igel-kun** [comment]
seems like all "Could you plese" points were implemented. I'm not sure if we have the fill-in solutions...

**Comment by holgerdell** [comment]
Indeed, this was done by Christian, thanks a lot! Solutions are not as important, because the solvers are available
